### ISSUE TITLE
Discordにて`/report`でカードを作った際に、Dynmapの画像が添付されない不具合

### ISSUE THREAD

**Issue by Omuretsu** [jaoafa/jaoTrello#5]
### 不具合の説明

表題のとおりです。

### 再現手順

Discord`#jaotan`にて、`/report <ID> <Reason>`を実行する。

**Comment by book000** [comment]
めも: jaotan作成カードの場合に作成時処理をしていないのが原因のようです
https://github.com/jaoafa/jaoTrello/blob/0e1954dddfcbfa61c07dfd71da305a6758dacaef/src/actions.py#L84
